<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class TemporarySong extends Model
{
    use HasFactory;

    protected $fillable = [
      'token',
      'filePath'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($file) {
            $file->token = Str::uuid();
        });
    }

}
